apiVersion: apps/v1
kind: Deployment
metadata:
  name: helmchart
spec:
  replicas: 1
  selector:
    matchLabels:
      name: helmchart
  template:
    metadata:
      labels:
        name: helmchart
    spec:
      serviceAccountName: helmchart
      containers:
        - name: helmchart
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - helmchart
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "helmchart"
