kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: helmchart
subjects:
- kind: ServiceAccount
  name: helmchart
roleRef:
  kind: Role
  name: helmchart
  apiGroup: rbac.authorization.k8s.io
